export const GET_COUNTRIES = 'GET_COUNTRIES';
export const SET_PAGINATION ='SET_PAGINATION';
export const GET_COUNTRIES_BY_NAME = 'GET_COUNTRIES_BY_NAME';
export const GET_COUNTRYDETAIL = 'GET_COUNTRYDETAIL';
export const FILTER_BY_CONTINENT = 'FILTER_BY_CONTINENT';